### ISSUE TITLE
COPY RELEASE /这个文件夹在哪？

### ISSUE THREAD

**Issue by kernelsky** [yuri-moe/gitlab-ce-arm64#1]
dockerfile构建的时候会报错缺少这个文件夹
COPY RELEASE /

**Comment by Adoream** [comment]
请参考
https://github.com/yuri-moe/gitlab-ce-arm64/blob/7a6682417540129c824ef8eee2cd9a73bc73646c/.github/workflows/build-docker-image.yml#L34-L38
